apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  restartPolicy: Never
  containers:
  - name: kibana
    image: kibana:7.3.0
    env:
      - name: ELASTICSEARCH_HOSTS
        value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - nodePort: 30002
      port: 80
      targetPort: 5601