apiVersion: v1
kind: Pod
metadata:
  name: server1
  labels:
    app: server1
spec:
  containers:
  - name: server1
    imagePullPolicy: Never
    image: goserver:latest
    ports:
      - containerPort: 80
    env:
      - name: SUCCESS_RATE
        value: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: test-server-service
spec:
  type: NodePort
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011